{{ if .Values.postInstall.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install-job"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
{{- if .Values.postInstall.labels }}
    {{- toYaml .Values.postInstall.labels | nindent 4 }}
{{- end }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
{{- if .Values.postInstall.annotations }}
    {{-- toYaml .Values.postInstall.annotations | nindent 4 }}
{{- end }}
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
{{- if .Values.postInstall.podAnnotations }}
      annotations:
        {{- toYaml .Values.postInstall.podAnnotations | nindent 8 }}
{{- end }}
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: {{ .Values.postInstall.image.repository }}:{{ .Values.postInstall.image.tag }}
        imagePullPolicy: {{ .Values.postInstall.image.pullPolicy }}
        command: ["/bin/sh", "-c", "sleep {{ .Values.postInstall.config.sleepTime | default .Values.configuration.vaultPostInstallSleepTime | default "120" }} && sh /tmp/init.sh"]
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        env:
        - name: VAULT_ADDR
          value: "{{ .Values.postInstall.config.vaultAddr | default .Values.configuration.vaultPostInstallEnvironment.vaultAddr | default (printf "http://%s-%s.%s.svc.cluster.local:8200" .Release.Name "vault" .Release.Namespace ) }}"
        - name: VAULT_SKIP_VERIFY
          value: "{{ .Values.postInstall.config.vaultSkipVerify | default .Values.configuration.vaultPostInstallEnvironment.vaultSkipVerify | default "true" }}"
        - name: VAULT_TOKEN
          value: "{{ .Values.postInstall.config.vaultToken | default .Values.configuration.vaultPostInstallEnvironment.vaultToken | default .Values.vault.server.dev.devRootToken }}"
        volumeMounts:
        - name: init-script
          mountPath: /tmp/
      volumes:
      - name: init-script
        configMap:
          name: {{ .Release.Name }}-toucan-authn-post-install-script
          items:
          - key: init.sh
            path: init.sh

{{- end -}}
