apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-toucan-authn-post-install-script
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  init.sh: |-
    #!/bin/sh
    set -e

    create_config_oauth_server_provider() {
      local tenant_uuid="$1"
      local client_id="$2"
      local client_secret="$3"

      vault write toucan_oauthapp_tenant/servers/${tenant_uuid}/${tenant_uuid}-oauth/${client_id} \
        provider=oidc \
        provider_options=issuer_url=http{{ if .Values.idsvr.ingress.runtime.secretName }}s{{ end }}://{{ .Values.idsvr.ingress.runtime.host }}/${tenant_uuid}/oauth/oauth-anonymous \
        client_id=${client_id} \
        client_secret=${client_secret}
    }

    create_self_oauth_client_credentials() {
      local tenant_uuid="$1"
      local client_id="$2"
      local scopes="$3"

      vault write toucan_oauthapp_tenant/self/${tenant_uuid}/${client_id} \
        server=${tenant_uuid}/${tenant_uuid}-oauth/${client_id} \
        scopes=${scopes}
    }

    create_super_admin_user() {
      local tenant_uuid="$1"
      local username="$2"
      local password="$3"
      local workspace="$4"

      local token=$(vault read -field="access_token" toucan_oauthapp_tenant/self/${tenant_uuid}/toucan-admin-management-client)

      curl --request POST \
        --url http{{ if .Values.idsvr.ingress.runtime.secretName }}s{{ end }}://{{ .Values.idsvr.ingress.runtime.host }}/${tenant_uuid}/user-management/graphql/admin \
        --header "Authorization: Bearer ${token}" \
        --header "Content-Type: application/json" \
        --data '{"query":"mutation {\n\tcreateAccount(\n\t\tinput: {\n\t\t\tfields: {\n\t\t\t\tuserName: \"'${username}'\"\n\t\t\t\temails: { value: \"'${username}'\", primary: true }\n\t\t\t\tactive: true\n\t\t\t\tpassword: \"'${password}'\"\n\t\t\t\tlegacyLaputaRoles: \"{\\\"workspace_'${workspace}'\\\":{\\\"roles\\\":[\\\"SUPER_ADMIN\\\"]}}\"\n\t\t\t}\n\t\t}\n\t) {\n\t\taccount {\n\t\t\tid\n\t\t\tuserName\n\t\t\tprofileUrl\n\t\t}\n\t}\n}\n"}'
    }

    # Install Curl
    apk update && apk add curl

    create_config_oauth_server_provider "{{ .Values.configuration.tenantId }}" "toucan-admin-management-client" "{{ .Values.configuration.oidcClients.toucanAdminManagementClient.secret }}"
    create_self_oauth_client_credentials "{{ .Values.configuration.tenantId }}" "toucan-admin-management-client" "accounts"

    create_config_oauth_server_provider "{{ .Values.configuration.tenantId }}" "toucan-micro-service-client" "{{ .Values.configuration.oidcClients.toucanMicroServiceClient.secret }}"
    create_self_oauth_client_credentials "{{ .Values.configuration.tenantId }}" "toucan-micro-service-client" "micro-service"

    {{- if not .Values.configuration.toucan.superAdminUser.existingSecret }}
    SUPER_ADMIN_PASSWORD="{{ .Values.configuration.toucan.superAdminUser.password }}"
    {{- end }}

    create_super_admin_user "{{ .Values.configuration.tenantId }}" "{{ .Values.configuration.toucan.superAdminUser.username }}" "${SUPER_ADMIN_PASSWORD}" "{{ .Values.configuration.workspaceId | replace "-" "" }}"
