{{- range $key, $value := .Values.storage }}
{{- if eq $value.type "PersistentVolume" }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "laputa.fullname" $ }}-{{ $key }}
  labels:
    app.kubernetes.io/component: {{ include "laputa.fullname" $ }}-laputa
    {{- include "laputa.labels" $ | nindent 4 }}
  annotations:
  {{- with $value.annotations }}
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  accessModes:
  {{- range $value.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $value.size | quote }}
{{- end }}
{{- end }}
