apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laputa.fullname" . }}-configuration
  labels:
    {{- include "laputa.labels" . | nindent 4 }}
data:
  TOUCAN_TENANCY:       {{ .Values.configuration.tenancy | toJson | b64enc | quote }}
  TOUCAN_DATA_SERVICES: {{ .Values.configuration.dataService | toJson | b64enc | quote }}
  TOUCAN_SPICEDB:       {{ .Values.configuration.spicedb | toJson | b64enc | quote }}
{{- range $k, $v := .Values.configuration.common }}
  {{ $k }}: '{{ $v | b64enc }}'
{{- end }}
