apiVersion: v2
name: laputa
description: A Helm chart for Laputa

type: application

version: 0.2.1

appVersion: "v129.0.2"

dependencies:
  # Redis 6.2
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    version: 16.13.2
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
    version: 13.18.5

keywords:
  - laputa
  - toucan

maintainers:
  - name: Toucan Toco
    email: infra@toucantoco.com
