apiVersion: v2
name: dataset
description: A Helm chart to deploy Toucan Dataset Service

type: application

appVersion: latest
version: 0.4.5

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 13.2.15
    condition: postgresql.enabled

maintainers: # (optional)
  - name: Toucan Toco
    email: infra@toucantoco.com
