apiVersion: v2
name: authN
description: A Helm for the Authentication Service

type: application

version: 0.1.0

appVersion: "latest"

dependencies:
  - name: idsvr
    repository: https://curityio.github.io/idsvr-helm
    version: 0.12.15
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.9.13
    condition: postgresql.enabled

keywords:
  - authN
  - toucan

maintainers:
  - name: Riadh Meghenem
    email: riadh.meghenem@toucantoco.com
