apiVersion: v2
name: authN
description: A Helm for the Authentication Service

type: application

version: 0.2.2

appVersion: "latest"

dependencies:
  - name: idsvr
    repository: https://curityio.github.io/idsvr-helm
    version: 0.12.15
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 13.2.15
    condition: postgresql.enabled
  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.23.0
    condition: vault.enabled

keywords:
  - authN
  - toucan

maintainers:
  - name: Toucan Toco
    email: infra@toucantoco.com
