---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dataset.fullname" . }}-config
  labels:
    {{- include "dataset.labels" . | nindent 4 }}
{{- with .Values.configMap.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
data:
  config.yml: |
    {{- toYaml .Values.configuration | nindent 4 }}
