---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dataset.fullname" . }}-config-gunicorn
  labels:
    {{- include "dataset.labels" . | nindent 4 }}
data:
  gunicorn.conf.py: |
  {{- range $k, $v := .Values.configGunicorn }}
    {{ $k }}={{ $v }}
  {{- end }}
