---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dataset.fullname" . }}-config-gunicorn
  labels:
    {{- include "dataset.labels" . | nindent 4 }}
{{- with .Values.gunicornConfigMap.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.gunicornConfigMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
data:
  gunicorn.conf.py: |
  {{- range $k, $v := .Values.configGunicorn }}
    {{ $k }}="{{ $v }}"
  {{- end }}
