apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dataset.fullname" . }}-env
  labels:
    {{- include "dataset.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.configuration }}
  {{ $k }}: '{{ $v }}'
{{- end }}