apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dataset.fullname" . }}
  labels:
    {{- include "dataset.labels" . | nindent 4 }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dataset.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        checksum/config-gunicorn: {{ include (print $.Template.BasePath "/config_gunicorn.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "dataset.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dataset.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-migration
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          command: ["/bin/sh", "-c", "/admin_scripts/run_migrations.sh"]
          volumeMounts:
            - name:      config
              mountPath: /config/config.yml
              subPath:   config.yml
            - name:      config-gunicorn
              mountPath: /config/gunicorn.conf.py
              subPath:   gunicorn.conf.py
            - name:      {{ include "dataset.fullname" . }}-spicedb-ca
              mountPath: /app/custom_certs
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name:      config
              mountPath: /config/config.yml
              subPath:   config.yml
            - name:      config-gunicorn
              mountPath: /config/gunicorn.conf.py
              subPath:   gunicorn.conf.py
            - name:      {{ include "dataset.fullname" . }}-spicedb-ca
              mountPath: /app/custom_certs
      volumes:
        - name: config
          configMap:
            name: {{ include "dataset.fullname" . }}-config
            items:
            - key: config.yml
              path: config.yml
        - name: config-gunicorn
          configMap:
            name: {{ include "dataset.fullname" . }}-config-gunicorn
        - name: {{ include "dataset.fullname" . }}-spicedb-ca
          secret:
            secretName: {{ include "dataset.fullname" . }}-spicedb-ca
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
