apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dataset.fullname" . }}-db
  labels:
    {{- include "dataset.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL:           "{{ printf "postgresql://%s:%s@%s-postgresql.%s.svc.cluster.local:%d/%s"  .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Release.Namespace  (.Values.postgresql.postgresqlPort | int) .Values.postgresql.auth.database | b64enc }}"
  DATABASE_URL_ADMIN:     "{{ printf "postgresql://%s:%s@%s-postgresql.%s.svc.cluster.local:%d/%s"  .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Release.Namespace  (.Values.postgresql.postgresqlPort | int) .Values.postgresql.auth.database | b64enc }}"
  {{- else }}
  DATABASE_URL:           "{{ printf "postgresql://%s:%s@%s:%d/%s"  .Values.postgresql.auth.username .Values.postgresql.auth.password .Values.postgresql.postgresqlHostname .Values.postgresql.auth.database | b64enc }}"
  DATABASE_URL_ADMIN:     "{{ printf "postgresql://%s:%s@%s:%d/%s"  .Values.postgresql.auth.username .Values.postgresql.auth.password .Values.postgresql.postgresqlHostname .Values.postgresql.auth.database | b64enc }}"
  {{- end }}