apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "layout.fullname" . }}-config
  labels:
    {{- include "layout.labels" . | nindent 4 }}
data:
  config.yml: >-
    auth:
      {{- toYaml .Values.configuration.auth | nindent 6 }}
    database_redis:
      {{- toYaml .Values.configuration.database_redis | nindent 6 }}
    environment:
      {{- toYaml .Values.configuration.environment | nindent 6 }}
    flagsmith:
      {{- toYaml .Values.configuration.flagsmith | nindent 6 }}
    log_level:
      {{- toYaml .Values.configuration.log_level | nindent 6 }}
    profiling:
      {{- toYaml .Values.configuration.profiling | nindent 6 }}
    specific:
      {{- toYaml .Values.configuration.specific | nindent 6 }}
    tracing:
      {{- toYaml .Values.configuration.tracing | nindent 6 }}
