apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "layout.fullname" . }}-config
  labels:
    {{- include "layout.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- toYaml .Values.configuration | nindent 4 }}
