{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: toucan-layout-psql-init
  labels:
    {{- include "layout.labels" . | nindent 4 }}
data:
  init.sql: |-
    \c "{{ .Values.postgresql.auth.database }}"
    CREATE SCHEMA IF NOT EXISTS "{{ .Values.postgresql.auth.schema }}";
{{- end }}