apiVersion: v1
kind: Secret
metadata:
  name: {{ include "layout.fullname" . }}-db
  labels:
    {{- include "layout.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL:           "{{ printf "postgresql://%s:%s@%s-postgresql.%s.svc.cluster.local:%d/%s?schema=%s"  .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Release.Namespace  (.Values.postgresql.postgresqlPort | int) .Values.postgresql.auth.database .Values.postgresql.auth.schema | b64enc }}"
  DATABASE_URL_ADMIN:     "{{ printf "postgresql://%s:%s@%s-postgresql.%s.svc.cluster.local:%d/%s?schema=%s"  .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Release.Namespace  (.Values.postgresql.postgresqlPort | int) .Values.postgresql.auth.database .Values.postgresql.auth.schema | b64enc }}"
  {{- else }}
  DATABASE_URL:           "{{ printf "postgresql://%s:%s@%s:%d/%s?schema=%s"  .Values.postgresql.auth.username .Values.postgresql.auth.password .Values.postgresql.postgresqlHostname (.Values.postgresql.postgresqlPort | int) .Values.postgresql.auth.database .Values.postgresql.auth.schema | b64enc }}"
  DATABASE_URL_ADMIN:     "{{ printf "postgresql://%s:%s@%s:%d/%s?schema=%s"  .Values.postgresql.auth.username .Values.postgresql.auth.password .Values.postgresql.postgresqlHostname (.Values.postgresql.postgresqlPort | int) .Values.postgresql.auth.database .Values.postgresql.auth.schema | b64enc }}"
  {{- end }}
