---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "layout.fullname" . }}-spicedb-ca
  labels:
    {{- include "layout.labels" . | nindent 4 }}
data:
  ca-spicedb.pem: {{ .Values.keys.spicedb.ca | b64enc }}
