apiVersion: v1
kind: Service
metadata:
  name: {{ include "authz.fullname" . }}-env
  labels:
    {{- include "authz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port:       {{ .Values.service.port }}
      targetPort: grpc
      protocol:   TCP
      name:       grpc
  selector:
    {{- include "authz.selectorLabels" . | nindent 4 }}
