apiVersion: v1
kind: Service
metadata:
  name: {{ include "authz.fullname" . }}
  labels:
    {{- include "authz.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port:       {{ .Values.service.port }}
      targetPort: grpc
      protocol:   TCP
      name:       grpc
  selector:
    {{- include "authz.selectorLabels" . | nindent 4 }}
