---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authz.fullname" . }}-tls
  labels:
    {{- include "authz.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
type: kubernetes.io/tls
