apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "impersonate.fullname" . }}
  labels:
    {{- include "impersonate.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "impersonate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configuration: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "impersonate.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "impersonate.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONFIG_PATH
              value: "/etc/impersonate-token-service/configuration/config.yaml"
          volumeMounts:
            - name: configuration-service
              mountPath: "/etc/impersonate-token-service/configuration/config.yaml"
              subPath: "config.yml"
            - name: configuration-service
              mountPath: "/etc/impersonate-token-service/keys/impersonate_user_rsa_4096_priv.pem"
              subPath: "impersonate-user-token-key.pem"
            - name: configuration-service
              mountPath: "/etc/impersonate-token-service/keys/embed_token_rsa_4096_priv.pem"
              subPath: "embed-token-key.pem"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: configuration-service
          secret:
            secretName: {{ include "impersonate.fullname" . }}-configuration
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
