apiVersion: v1
kind: Secret
metadata:
  name: {{ include "impersonate.fullname" . }}-configuration
  labels:
    {{- include "impersonate.labels" . | nindent 4 }}
data:
  config.yml: {{ .Values.configuration | toYaml | b64enc }}
  impersonate-user-token-key.pem: {{ .Values.keys.impersonateUserTokenRsaKey | b64enc }}
  embed-token-key.pem: {{ .Values.keys.embedTokenRsaKey | b64enc }}