apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tucana.fullname" . }}
  labels:
    {{- include "tucana.labels" . | nindent 4 }}
data:
  tc-params.js: |
    {{ .Values.tucana_configuration | nindent 4 }}